version: '3.4'
services:
  db:
    image: mariadb:10.3.38-focal
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: termostat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: on-failure